# Form implementation generated from reading ui file 'projectx.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth()
        )
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.prompt_frame = QtWidgets.QFrame(parent=self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prompt_frame.sizePolicy().hasHeightForWidth())
        self.prompt_frame.setSizePolicy(sizePolicy)
        self.prompt_frame.setObjectName("prompt_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.prompt_frame)
        self.verticalLayout.setContentsMargins(-1, 12, -1, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.prompt_frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.promptInput = QtWidgets.QTextEdit(parent=self.prompt_frame)
        self.promptInput.setObjectName("promptInput")
        self.verticalLayout.addWidget(self.promptInput)
        self.generateButton = QtWidgets.QPushButton(parent=self.prompt_frame)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)
        self.label_4 = QtWidgets.QLabel(parent=self.prompt_frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.llmOutput = QtWidgets.QTextBrowser(parent=self.prompt_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.llmOutput.sizePolicy().hasHeightForWidth())
        self.llmOutput.setSizePolicy(sizePolicy)
        self.llmOutput.setObjectName("llmOutput")
        self.verticalLayout.addWidget(self.llmOutput)
        self.horizontalLayout_4.addWidget(self.prompt_frame)
        self.config_files_frame = QtWidgets.QFrame(parent=self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(
            self.config_files_frame.sizePolicy().hasHeightForWidth()
        )
        self.config_files_frame.setSizePolicy(sizePolicy)
        self.config_files_frame.setObjectName("config_files_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.config_files_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.old_config_frame = QtWidgets.QFrame(parent=self.config_files_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.old_config_frame.sizePolicy().hasHeightForWidth()
        )
        self.old_config_frame.setSizePolicy(sizePolicy)
        self.old_config_frame.setObjectName("old_config_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.old_config_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.old_config_frame)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.oldConfigText = QtWidgets.QTextBrowser(parent=self.old_config_frame)
        self.oldConfigText.setObjectName("oldConfigText")
        self.verticalLayout_3.addWidget(self.oldConfigText)
        self.horizontalLayout_3.addWidget(self.old_config_frame)
        self.new_config_frame = QtWidgets.QFrame(parent=self.config_files_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.new_config_frame.sizePolicy().hasHeightForWidth()
        )
        self.new_config_frame.setSizePolicy(sizePolicy)
        self.new_config_frame.setObjectName("new_config_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.new_config_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.new_config_frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.newConfigText = QtWidgets.QTextBrowser(parent=self.new_config_frame)
        self.newConfigText.setObjectName("newConfigText")
        self.verticalLayout_2.addWidget(self.newConfigText)
        self.horizontalLayout_3.addWidget(self.new_config_frame)
        self.new_config_frame.raise_()
        self.old_config_frame.raise_()
        self.horizontalLayout_4.addWidget(self.config_files_frame)
        self.verticalLayout_4.addWidget(self.main_frame)
        self.save_buttons_frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.save_buttons_frame.sizePolicy().hasHeightForWidth()
        )
        self.save_buttons_frame.setSizePolicy(sizePolicy)
        self.save_buttons_frame.setObjectName("save_buttons_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.save_buttons_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.cancel_button = QtWidgets.QPushButton(parent=self.save_buttons_frame)
        self.cancel_button.setEnabled(False)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.apply_button = QtWidgets.QPushButton(parent=self.save_buttons_frame)
        self.apply_button.setEnabled(False)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_2.addWidget(self.apply_button)
        self.verticalLayout_4.addWidget(self.save_buttons_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Prompt"))
        self.promptInput.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.promptInput.setPlaceholderText(
            _translate("MainWindow", "Your prompt here...")
        )
        self.generateButton.setText(_translate("MainWindow", "Generate"))
        self.label_4.setText(_translate("MainWindow", "LLM output"))
        self.llmOutput.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Noto Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                '<h1 style="-qt-paragraph-type:empty; margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:xx-large; font-weight:700;"><br /></h1></body></html>',
            )
        )
        self.llmOutput.setPlaceholderText(
            _translate("MainWindow", "LLM generated configuration...")
        )
        self.label.setText(_translate("MainWindow", "Current nix configuration"))
        self.label_2.setText(_translate("MainWindow", "New nix configuration"))
        self.newConfigText.setPlaceholderText(
            _translate("MainWindow", "No configuration generated yet...")
        )
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.apply_button.setText(_translate("MainWindow", "Apply"))
